// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_oVfDlJYpJY_EiPsPVjTqHoIjidU1OCU',
    appId: '1:849648091245:web:738dc8cb7997159dd97f64',
    messagingSenderId: '849648091245',
    projectId: 'file-sharing-f98e4',
    authDomain: 'file-sharing-f98e4.firebaseapp.com',
    storageBucket: 'file-sharing-f98e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_BFcadYvwjqcqwJcNICwyd1SLGeeThU',
    appId: '1:849648091245:android:d78042b8699e24a3d97f64',
    messagingSenderId: '849648091245',
    projectId: 'file-sharing-f98e4',
    storageBucket: 'file-sharing-f98e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfdtADqb7VHHzi4TZy46A2odqda8S2v4',
    appId: '1:849648091245:ios:4aedfd6bb240937bd97f64',
    messagingSenderId: '849648091245',
    projectId: 'file-sharing-f98e4',
    storageBucket: 'file-sharing-f98e4.appspot.com',
    iosClientId: '849648091245-7jh5hfuicpidh5ilsvjvjd965pjm4eet.apps.googleusercontent.com',
    iosBundleId: 'com.mukund.goalLock',
  );
}
